// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _solar_serverProxy_h_
#define _solar_serverProxy_h_

#include <staff/client/ServiceClient.h>
#include "solar_server.h"


//! Proxy for component service solar_server
class solar_serverProxy: public solar_server
{
public:
  solar_serverProxy();
  virtual ~solar_serverProxy();
  void Init(const std::string& sServiceUri, const std::string& sSessionId, const std::string& sInstanceId);
  void Deinit();
  virtual staff::ServiceClient* GetClient();
  double solarcreate();
  int solarinit(int gen_mode_v, int gen_status_v, int panel_type_v);
  double solarsync(int t0, int t1);
private:
  mutable staff::ServiceClient m_tClient;
  std::string m_sServiceUri;
};


namespace staff
{
  class DataObject;
}

#endif

